name = "enthusia-site"
pages_build_output_dir = "dist/client"
compatibility_date = "2025-09-08"

[env.production.vars]
GUILDS_API_URL = "http://api.enthusia.info:2052/api/leaderboards/guilds?period=ALL_TIME&limit=10"

[[env.production.r2_buckets]]
bucket_name = "balance-leaderboard"
binding = "BALANCE_LEADERBOARDS"

[[env.production.r2_buckets]]
bucket_name = "donator-leaderboard"
binding = "DONATOR_LEADERBOARDS"

[[env.production.r2_buckets]]
bucket_name = "playtime-leaderboard"
binding = "PLAYTIME_LEADERBOARDS"
